version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      # Upgrading SAM CLI to latest version
      - pip3 install --upgrade aws-sam-cli
      - sam --version
      - npm install
  pre_build:
    commands:
      - npm run check
      # Discover and run unit tests in the '__tests__' directory
      - npm run test
      # Remove mock files because we don't want to upload them
      - find . -name __mocks__ -type d -exec rm -rf {} +
      - npm run build
  build:
    commands:
      # Use AWS SAM to package the application by using AWS CloudFormation
      - sam build --parallel
  post_build:
    commands:
      - sam package --s3-bucket $PACKAGE_BUCKET --output-template-file packaged.yaml
artifacts:
  discard-paths: yes
  files:
    - packaged.yaml
    - prod-config.json
