version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm ci
      - npm run install:all
  pre_build:
    commands:
      - npm run check
  build:
    commands:
      # Use AWS SAM to package the application by using AWS CloudFormation
      - sam build --parallel
  post_build:
    commands:
      - sam package --s3-bucket $PACKAGE_BUCKET --output-template-file packaged.yaml
artifacts:
  discard-paths: yes
  files:
    - packaged.yaml
    - prod-config.json
