AWSTemplateFormatVersion: 2010-09-09
Description: >
  ordsky-apiv2
  Handles word cloud sessions for ordsky.no
Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  AmazonAPIGatewayPushToCloudWatchLogs:
    Type: String
    Description: The arn of the managed apigateway push to cloudwatch logs policy
  OrdskyACM:
    Type: String
    Description: The id of the ordsky certificate in ACM

Globals:
  Function:
    Runtime: nodejs18.x
    Handler: index.handler
    Tracing: Active
    Layers:
      - !Ref OrdskyDepLayer
    MemorySize: 1024
    AutoPublishAlias: Prod
    Environment:
      Variables:
        SESSION_TABLE: !Ref OrdskySessionTable
        ENDPOINT: !Sub 'https://${OrdskyDomainName}'
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1 # This lets lambda reuse connections (setting https to keep-alive). This hopefully speeds up dynamodb queries.

Resources:
  CloudWatchLogsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: Lets API Gateway push to CloudWatch logs
      ManagedPolicyArns:
        - !Ref AmazonAPIGatewayPushToCloudWatchLogs

  ApiGatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt CloudWatchLogsRole.Arn

  OrdskyDomainName:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: api.ordsky.no
      DomainNameConfigurations:
        - CertificateArn: !Sub arn:aws:acm:eu-north-1:${AWS::AccountId}:certificate/${OrdskyACM}
          CertificateName: ordsky
          EndpointType: REGIONAL
          SecurityPolicy: TLS_1_2

  OrdskyWebsocket:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: OrdskyWebsocket
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: '$request.body.action'

  StartSessionRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref OrdskyWebsocket
      RouteKey: startsession
      RouteResponseSelectionExpression: $default
      AuthorizationType: NONE
      OperationName: StartSessionRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref StartSessionInteg
  StartSessionInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref OrdskyWebsocket
      Description: Start Session Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${StartSessionFunction.Arn}/invocations
  StartSessionIntegResponse:
    Type: AWS::ApiGatewayV2::IntegrationResponse
    Properties:
      IntegrationId: !Ref StartSessionInteg
      ApiId: !Ref OrdskyWebsocket
      IntegrationResponseKey: $default
  StartSessionResponseRoute:
    Type: AWS::ApiGatewayV2::RouteResponse
    Properties:
      ApiId: !Ref OrdskyWebsocket
      RouteId: !Ref StartSessionRoute
      RouteResponseKey: $default

  SaveWordsRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref OrdskyWebsocket
      RouteKey: savewords
      AuthorizationType: NONE
      OperationName: SaveWordsRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref SaveWordsInteg
  SaveWordsInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref OrdskyWebsocket
      Description: Save Words Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SaveWordsFunction.Arn}/invocations

  GetWordsRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref OrdskyWebsocket
      RouteKey: getwords
      RouteResponseSelectionExpression: $default
      AuthorizationType: NONE
      OperationName: GetWordsRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref GetWordsInteg
  GetWordsInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref OrdskyWebsocket
      Description: Get Words Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetWordsFunction.Arn}/invocations
  GetWordsResponseRoute:
    Type: AWS::ApiGatewayV2::RouteResponse
    Properties:
      ApiId: !Ref OrdskyWebsocket
      RouteId: !Ref GetWordsRoute
      RouteResponseKey: $default

  SaveCloudRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref OrdskyWebsocket
      RouteKey: savecloud
      AuthorizationType: NONE
      OperationName: SaveCloudRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref SaveCloudInteg
  SaveCloudInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref OrdskyWebsocket
      Description: Save Cloud Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HandleCloudFunction.Arn}/invocations

  Deployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
      - StartSessionRoute
      - SaveWordsRoute
      - SaveCloudRoute
    Properties:
      ApiId: !Ref OrdskyWebsocket
  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: Prod
      Description: Prod Stage
      DeploymentId: !Ref Deployment
      ApiId: !Ref OrdskyWebsocket
      DefaultRouteSettings:
        LoggingLevel: INFO

  OrdskyApiMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties:
      ApiId: !Ref OrdskyWebsocket
      DomainName: api.ordsky.no
      Stage: !Ref Stage

  StartSessionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/start-session/
      Timeout: 1
      Description: Saves admin connection Id to table
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OrdskySessionTable
      Architectures:
        - arm64
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - index.ts
        External:
          - 'aws-xray-sdk'
          - '@aws-sdk'

  StartSessionPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - OrdskyWebsocket
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref StartSessionFunction
      Principal: apigateway.amazonaws.com

  SaveWordsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/save-words/
      Timeout: 2
      Description: Save words to a DynamoDB table.
      Architectures:
        - arm64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OrdskySessionTable
        - Statement: # TODO: Make this a policy document
            - Effect: Allow
              Action:
                - 'execute-api:ManageConnections'
              Resource:
                - !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${OrdskyWebsocket}/*'
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - index.ts
        External:
          - 'gw-helpers'
          - 'aws-xray-sdk'
          - '@aws-sdk'
  SaveWordsPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - OrdskyWebsocket
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref SaveWordsFunction
      Principal: apigateway.amazonaws.com

  GetWordsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/get-words/
      Timeout: 1
      Description: Get words from table.
      Architectures:
        - arm64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OrdskySessionTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - index.ts
        External:
          - 'aws-xray-sdk'
          - '@aws-sdk'
  GetWordsPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - OrdskyWebsocket
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref GetWordsFunction
      Principal: apigateway.amazonaws.com

  HandleCloudFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handle-cloud/
      Timeout: 3
      Description: Sends cloud to connections and saves cloud to DynamoDB table.
      Architectures:
        - arm64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OrdskySessionTable
        - Statement:
            - Effect: Allow
              Action:
                - 'execute-api:ManageConnections'
              Resource:
                - !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${OrdskyWebsocket}/*'
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - index.ts
        External:
          - 'gw-helpers'
          - 'aws-xray-sdk'
          - '@aws-sdk'

  HandleCloudPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - OrdskyWebsocket
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref HandleCloudFunction
      Principal: apigateway.amazonaws.com

  OrdskyDepLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: ordsky-no-dependencies
      Description: Dependencies for ordsky session api
      ContentUri: src/common/
      CompatibleRuntimes:
        - nodejs18.x
      LicenseInfo: 'MIT'
      RetentionPolicy: Delete #Could also be Retain if I want to keep every version..
    Metadata:
      BuildMethod: makefile

  # DynamoDB table to store words and clouds
  OrdskySessionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: OrdskySession
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 3
        WriteCapacityUnits: 3
      TimeToLiveSpecification:
        AttributeName: expdate
        Enabled: True

  OrdskySessionWriteCapacityScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    DependsOn: OrdskySessionTable
    Properties:
      MaxCapacity: 8
      MinCapacity: 3
      ResourceId: !Sub table/${OrdskySessionTable}
      RoleARN: !Sub arn:aws:iam::${AWS::AccountId}:role/aws-service-role/dynamodb.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_DynamoDBTable
      ScalableDimension: 'dynamodb:table:WriteCapacityUnits'
      ServiceNamespace: dynamodb
      ScheduledActions:
        - ScalableTargetAction:
            MaxCapacity: 10
            MinCapacity: 5
          Schedule: cron(0 8-17 ? * MON-FRI *) # Every mon-fri 8-17
          ScheduledActionName: Weekly autoscaling
        - ScalableTargetAction:
            MaxCapacity: 3
          Schedule: cron(0 17 ? * MON-FRI *) # We want to scale down outside of the hours above
          ScheduledActionName: Weekly descaling

  OrdskySessionWriteScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: WriteAutoScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref OrdskySessionWriteCapacityScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 70 # means 70 percent of the current provisioned throughput
        ScaleInCooldown: 60
        ScaleOutCooldown: 60
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBWriteCapacityUtilization

Outputs:
  WebSocketURI:
    Description: 'API Gateway endpoint URL for Prod stage'
    Value: !Sub 'wss://${OrdskyWebsocket}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/'
